(()=>{
  function openPrintWindow(title){
    const w=window.open('', '_blank');
    if(!w){ if(typeof toast==='function') toast('Allow pop-ups to print','warn'); return null; }
    w.document.open();
    return w;
  }
  function businessName(){
    return (STATE&&STATE.settings&&STATE.settings.businessName)||'Command de Cuisine';
  }
  function generatedBy(){
    const who=(typeof ME!=='undefined'&&ME&&(ME.name||ME.username))||(typeof CURRENT_USER!=='undefined'&&CURRENT_USER?.name)||'';
    return who?` · generated by ${esc(who)}`:'';
  }
  function printAllergenMatrix(){
    const w=openPrintWindow('Allergen matrix'); if(!w)return;
    const rows=(STATE.recipes||[]).map(r=>`<tr><td class="dish">${esc(r.name||'Untitled')}</td>${ALLERGENS.map(a=>`<td class="mark">${recipeHas(r,a)?'●':''}</td>`).join('')}</tr>`).join('');
    w.document.write(`<html><head><title>Allergen matrix — ${esc(businessName())}</title><style>
      @page{size:A4 landscape;margin:10mm}body{font-family:Arial,sans-serif;color:#111;margin:0;font-size:9px}h1{font-size:20px;margin:0 0 3px}.sub{font-size:10px;color:#555;margin-bottom:10px}.warning{border:1px solid #111;padding:7px 9px;margin:0 0 10px;font-size:9px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #777;padding:4px 2px;text-align:center}th{background:#eee;font-size:8px}.dish{text-align:left;width:23%;font-weight:600}.mark{font-size:13px}.foot{margin-top:8px;font-size:8px;color:#555}
    </style></head><body><h1>${esc(businessName())} — Allergen matrix</h1><div class="sub">14 regulated allergens · printed ${new Date().toLocaleString('en-GB')}${generatedBy()}</div><div class="warning"><b>Important:</b> This matrix reflects the allergen information currently recorded in Command de Cuisine. Verify recipes, supplier specifications and ingredient changes before relying on it for service.</div><table><thead><tr><th class="dish">Dish</th>${ALLERGENS.map(a=>`<th>${esc(a)}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="15">No recipes recorded</td></tr>'}</tbody></table><div class="foot">● = allergen recorded as present for that dish.</div><script>setTimeout(()=>window.print(),350)<\/script></body></html>`);
    w.document.close();
  }
  function printDishAllergens(){
    const w=openPrintWindow('Dish allergen sheets'); if(!w)return;
    const cards=(STATE.recipes||[]).map(r=>{
      const present=ALLERGENS.filter(a=>recipeHas(r,a));
      const marks=ALLERGENS.map(a=>`<div class="a ${recipeHas(r,a)?'on':''}"><span>${recipeHas(r,a)?'●':'○'}</span>${esc(a)}</div>`).join('');
      return `<section class="dish-card"><h2>${esc(r.name||'Untitled dish')}</h2><div class="present"><b>Recorded allergens:</b> ${present.length?present.map(esc).join(', '):'None recorded'}</div><div class="grid">${marks}</div><div class="verify">Check the current recipe, ingredient labels and supplier specifications before service. Update Command de Cuisine whenever ingredients or suppliers change.</div></section>`;
    }).join('');
    w.document.write(`<html><head><title>Dish allergen sheets — ${esc(businessName())}</title><style>
      @page{size:A4 portrait;margin:12mm}body{font-family:Arial,sans-serif;color:#111;margin:0}.header{margin-bottom:12px}.header h1{font-size:20px;margin:0}.sub{font-size:10px;color:#555;margin-top:3px}.dish-card{border:2px solid #111;padding:14px;margin:0 0 12px;break-inside:avoid;page-break-inside:avoid}.dish-card h2{font-size:18px;margin:0 0 8px}.present{font-size:12px;margin-bottom:10px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:5px 16px}.a{border:1px solid #bbb;padding:6px 8px;font-size:11px}.a span{display:inline-block;width:18px}.a.on{font-weight:700;border:2px solid #111}.verify{font-size:9px;margin-top:10px;padding-top:8px;border-top:1px solid #999;color:#444}
    </style></head><body><div class="header"><h1>${esc(businessName())} — Dish allergen sheets</h1><div class="sub">Printed ${new Date().toLocaleString('en-GB')}${generatedBy()}</div></div>${cards||'<p>No recipes recorded.</p>'}<script>setTimeout(()=>window.print(),350)<\/script></body></html>`);
    w.document.close();
  }
  window.printAllergenMatrix=printAllergenMatrix;
  window.printDishAllergens=printDishAllergens;

  if(typeof VIEWS!=='undefined'&&VIEWS.allergens){
    const original=VIEWS.allergens;
    VIEWS.allergens=function(v){
      original(v);
      const card=v.querySelector('.card');
      if(!card)return;
      const bar=document.createElement('div');
      bar.style.cssText='display:flex;gap:10px;flex-wrap:wrap;padding:0 16px 16px';
      const matrix=document.createElement('button');
      matrix.className='btn primary'; matrix.type='button'; matrix.innerHTML=(typeof icon==='function'?icon('print'):'')+'Print full allergen matrix'; matrix.onclick=printAllergenMatrix;
      const dishes=document.createElement('button');
      dishes.className='btn ghost'; dishes.type='button'; dishes.innerHTML=(typeof icon==='function'?icon('print'):'')+'Print dish allergen sheets'; dishes.onclick=printDishAllergens;
      bar.append(matrix,dishes); card.append(bar);
    };
  }
})();
