/* Command de Cuisine — manager controls v5.
   Always-visible manager button on Cleaning Schedule / Daily Checks.
   Edits active definitions only; historic completion records are preserved. */
(function(){
  'use strict';
  function st(){
    try{if(typeof STATE!=='undefined'&&STATE&&typeof STATE==='object')return STATE;}catch(e){}
    try{if(typeof state!=='undefined'&&state&&typeof state==='object')return state;}catch(e){}
    return window.STATE||window.state||null;
  }
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function toastMsg(t,k){try{if(typeof toast==='function')return toast(t,k||'ok');}catch(e){} alert(t);}
  async function persist(t){if(typeof save!=='function')throw new Error('Save function unavailable');var r=save();if(r&&typeof r.then==='function')await r;if(t)toastMsg(t,'ok');}
  function kind(){var txt=String(document.body&&document.body.innerText||'').toLowerCase();if(txt.indexOf('cleaning schedule')>=0)return'cleaning';if(txt.indexOf('daily checks')>=0)return'daily';return'';}
  function css(){if(document.getElementById('cdc-v5-css'))return;var x=document.createElement('style');x.id='cdc-v5-css';x.textContent='.cdc-v5-fab{position:fixed!important;left:16px!important;bottom:88px!important;z-index:2147483000!important;background:#e3ad35!important;color:#17191d!important;border:2px solid #f3c85d!important;border-radius:15px!important;padding:13px 17px!important;font-size:15px!important;font-weight:900!important;box-shadow:0 8px 28px rgba(0,0,0,.55)!important;min-width:155px!important}.cdc-v5-overlay{position:fixed;inset:0;z-index:2147483640;background:rgba(0,0,0,.78);display:flex;align-items:flex-end;justify-content:center;padding:10px}.cdc-v5-sheet{width:min(720px,100%);max-height:90vh;overflow:auto;background:#181c22;color:#f4f4f4;border:1px solid #3b4450;border-radius:18px 18px 8px 8px;padding:16px}.cdc-v5-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.cdc-v5-head h2{margin:0}.cdc-v5-close,.cdc-v5-edit,.cdc-v5-remove,.cdc-v5-save,.cdc-v5-cancel{border-radius:10px;padding:9px 12px;font-weight:800;border:1px solid #4c5664;background:#2a3039;color:white}.cdc-v5-remove{border-color:#9b4848;color:#ff9b9b}.cdc-v5-save{background:#e3ad35;color:#17191d;border-color:#e3ad35}.cdc-v5-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;background:#20252d;border:1px solid #353e49;border-radius:12px;padding:12px;margin:8px 0}.cdc-v5-row small{display:block;opacity:.72;margin-top:4px}.cdc-v5-actions{display:flex;gap:7px;flex-wrap:wrap}.cdc-v5-form{display:grid;gap:12px}.cdc-v5-form label{display:grid;gap:6px;font-weight:800}.cdc-v5-form input,.cdc-v5-form select{width:100%;box-sizing:border-box;padding:11px;border-radius:10px;border:1px solid #46515f;background:#101319;color:white;font:inherit}.cdc-v5-form-actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:560px){.cdc-v5-row{grid-template-columns:1fr}.cdc-v5-fab{bottom:82px!important;left:12px!important;min-width:145px!important}}';document.head.appendChild(x);}
  function close(){var o=document.getElementById('cdc-v5-overlay');if(o)o.remove();}
  function sheet(title,html){close();var o=document.createElement('div');o.id='cdc-v5-overlay';o.className='cdc-v5-overlay';o.innerHTML='<div class="cdc-v5-sheet"><div class="cdc-v5-head"><h2>'+esc(title)+'</h2><button class="cdc-v5-close">Close</button></div><div>'+html+'</div></div>';o.onclick=function(e){if(e.target===o)close();};o.querySelector('.cdc-v5-close').onclick=close;document.body.appendChild(o);return o;}
  function schedules(){var s=st();return s&&Array.isArray(s.cleaningSchedules)?s.cleaningSchedules:[];}
  function tasks(){var s=st();return s&&Array.isArray(s.cleaningTasks)?s.cleaningTasks:[];}
  function checks(){var s=st();return s&&Array.isArray(s.checks)?s.checks:[];}
  function matchTask(s){return tasks().find(function(t){return t&&String(t.area||'')===String(s.area||'')&&String(t.task||'')===String(s.task||'');})||null;}
  function cleanList(){var a=schedules();var html=a.length?a.map(function(s,i){var f=s.frequency||s.freq||'';return '<div class="cdc-v5-row"><div><b>'+esc(s.task||'Cleaning task')+'</b><small>'+esc((s.area||'')+(f?' · '+f:''))+'</small></div><div class="cdc-v5-actions"><button class="cdc-v5-edit" data-ce="'+i+'">Edit</button><button class="cdc-v5-remove" data-cr="'+i+'">Remove</button></div></div>';}).join(''):'<p>No active cleaning tasks.</p>';var o=sheet('Manage cleaning tasks',html);o.querySelectorAll('[data-ce]').forEach(function(b){b.onclick=function(){editClean(Number(b.dataset.ce));};});o.querySelectorAll('[data-cr]').forEach(function(b){b.onclick=function(){removeClean(Number(b.dataset.cr));};});}
  function editClean(i){var a=schedules(),s=a[i];if(!s)return toastMsg('Cleaning task not found','bad');var f=String(s.frequency||s.freq||'Daily').toLowerCase();var o=sheet('Edit cleaning task','<form id="cdc-v5-cf" class="cdc-v5-form"><label>Task<input name="task" required value="'+esc(s.task||'')+'"></label><label>Area / equipment<input name="area" required value="'+esc(s.area||'')+'"></label><label>Frequency<select name="frequency"><option'+(f==='daily'?' selected':'')+'>Daily</option><option'+(f==='weekly'?' selected':'')+'>Weekly</option><option'+(f==='monthly'?' selected':'')+'>Monthly</option></select></label><div class="cdc-v5-form-actions"><button type="button" class="cdc-v5-cancel">Cancel</button><button class="cdc-v5-save">Save changes</button></div></form>');o.querySelector('.cdc-v5-cancel').onclick=cleanList;o.querySelector('#cdc-v5-cf').onsubmit=async function(e){e.preventDefault();var fd=new FormData(e.target),n=String(fd.get('task')||'').trim(),area=String(fd.get('area')||'').trim(),freq=String(fd.get('frequency')||'Daily');if(!n||!area)return;var old=JSON.parse(JSON.stringify(s)),t=matchTask(s),oldt=t?JSON.parse(JSON.stringify(t)):null;try{s.task=n;s.area=area;s.frequency=freq;if('freq'in s)s.freq=freq.toLowerCase();if(t){t.task=n;t.area=area;t.freq=freq.toLowerCase();if('frequency'in t)t.frequency=freq;}await persist('Cleaning task updated');close();if(typeof render==='function')render();}catch(err){Object.assign(s,old);if(t&&oldt)Object.assign(t,oldt);toastMsg(err.message||'Could not update cleaning task','bad');}};}
  async function removeClean(i){var stateObj=st(),a=schedules(),s=a[i];if(!s)return toastMsg('Cleaning task not found','bad');if(!confirm('Remove “'+(s.task||'this cleaning task')+'” from the active cleaning schedule?\n\nHistoric completed records will remain.'))return;var bs=JSON.parse(JSON.stringify(a)),bt=JSON.parse(JSON.stringify(tasks())),t=matchTask(s);try{stateObj.cleaningSchedules=a.filter(function(_,idx){return idx!==i;});if(t){var ti=tasks().indexOf(t);stateObj.cleaningTasks=bt.filter(function(_,idx){return idx!==ti;});}await persist('Cleaning task removed');close();if(typeof render==='function')render();}catch(err){stateObj.cleaningSchedules=bs;stateObj.cleaningTasks=bt;toastMsg(err.message||'Could not remove cleaning task','bad');}}
  function dailyList(){var a=checks();var html=a.length?a.map(function(c,i){var p=String(c.period||'').toLowerCase()==='close'?'Closing':'Opening';return '<div class="cdc-v5-row"><div><b>'+esc(c.name||'Check')+'</b><small>'+p+'</small></div><div class="cdc-v5-actions"><button class="cdc-v5-edit" data-de="'+i+'">Edit</button><button class="cdc-v5-remove" data-dr="'+i+'">Remove</button></div></div>';}).join(''):'<p>No active daily checks.</p>';var o=sheet('Manage daily checks',html);o.querySelectorAll('[data-de]').forEach(function(b){b.onclick=function(){editDaily(Number(b.dataset.de));};});o.querySelectorAll('[data-dr]').forEach(function(b){b.onclick=function(){removeDaily(Number(b.dataset.dr));};});}
  function editDaily(i){var a=checks(),c=a[i];if(!c)return toastMsg('Daily check not found','bad');var cl=String(c.period||'').toLowerCase()==='close';var o=sheet('Edit daily check','<form id="cdc-v5-df" class="cdc-v5-form"><label>Check name<input name="name" required value="'+esc(c.name||'')+'"></label><label>When<select name="period"><option value="open"'+(!cl?' selected':'')+'>Opening</option><option value="close"'+(cl?' selected':'')+'>Closing</option></select></label><div class="cdc-v5-form-actions"><button type="button" class="cdc-v5-cancel">Cancel</button><button class="cdc-v5-save">Save changes</button></div></form>');o.querySelector('.cdc-v5-cancel').onclick=dailyList;o.querySelector('#cdc-v5-df').onsubmit=async function(e){e.preventDefault();var fd=new FormData(e.target),n=String(fd.get('name')||'').trim(),p=String(fd.get('period')||'open');if(!n)return;var old=JSON.parse(JSON.stringify(c));try{c.name=n;c.period=p;await persist('Daily check updated');close();if(typeof render==='function')render();}catch(err){Object.assign(c,old);toastMsg(err.message||'Could not update daily check','bad');}};}
  async function removeDaily(i){var stateObj=st(),a=checks(),c=a[i];if(!c)return toastMsg('Daily check not found','bad');if(!confirm('Remove “'+(c.name||'this daily check')+'” from the active Daily Checks list?\n\nHistoric completed records will remain.'))return;var before=JSON.parse(JSON.stringify(a));try{stateObj.checks=a.filter(function(_,idx){return idx!==i;});await persist('Daily check removed');close();if(typeof render==='function')render();}catch(err){stateObj.checks=before;toastMsg(err.message||'Could not remove daily check','bad');}}
  function ensure(){css();var k=kind(),b=document.getElementById('cdc-v5-fab');if(!k||!st()){if(b)b.remove();return;}if(b&&b.dataset.kind===k)return;if(b)b.remove();b=document.createElement('button');b.id='cdc-v5-fab';b.className='cdc-v5-fab';b.dataset.kind=k;b.type='button';b.textContent=k==='cleaning'?'MANAGE TASKS':'MANAGE CHECKS';b.onclick=k==='cleaning'?cleanList:dailyList;document.body.appendChild(b);}
  window.CDCManagerControlsV5={cleaning:cleanList,daily:dailyList};
  function start(){ensure();new MutationObserver(function(){setTimeout(ensure,0);}).observe(document.documentElement,{childList:true,subtree:true});setInterval(ensure,700);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();